version: '3.7'
networks:
  mongo-net:
    name: mongo-net
services:
  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:4.2.3
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/file.key", "--replSet", "rs", "--journal", "--bind_ip_all" ]
    ports:
    - "27018:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./scripts/file.key:/data/fle.key"

  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:4.2.3
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/file.key", "--replSet", "rs", "--journal", "--bind_ip_all" ]
    ports:
    - "27019:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
      - "./scripts/file.key:/data/file.key"

  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:4.2.3
    command: bash -c "/usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all" 
    ports:
    - "27017:27017"
    links:
    - mongo2:mongo2
    - mongo3:mongo3
    restart: always
    networks:
      - mongo-net
    volumes:
      - "./scripts/setup.sh:/scripts/setup.sh"
      - "./scripts/file.key:/data/file.key"
      - mongo-data:/data/db
volumes:
  mongo-data: